/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: suVPi77vb6vv9K5rYJwyxC
// Component: kUkUBFksmGv2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectcss
import sty from "./Plasmic_3DIcon.module.css"; // plasmic-import: kUkUBFksmGv2/css

createPlasmicElementProxy;

export type Plasmic_3DIcon__VariantMembers = {
  sms: "sms";
  icon: "sms" | "telegram" | "notification";
};
export type Plasmic_3DIcon__VariantsArgs = {
  sms?: SingleBooleanChoiceArg<"sms">;
  icon?: SingleChoiceArg<"sms" | "telegram" | "notification">;
};
type VariantPropType = keyof Plasmic_3DIcon__VariantsArgs;
export const Plasmic_3DIcon__VariantProps = new Array<VariantPropType>(
  "sms",
  "icon"
);

export type Plasmic_3DIcon__ArgsType = {};
type ArgPropType = keyof Plasmic_3DIcon__ArgsType;
export const Plasmic_3DIcon__ArgProps = new Array<ArgPropType>();

export type Plasmic_3DIcon__OverridesType = {
  root?: Flex__<"div">;
};

export interface Default_3DIconProps {
  sms?: SingleBooleanChoiceArg<"sms">;
  icon?: SingleChoiceArg<"sms" | "telegram" | "notification">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_3DIcon__RenderFunc(props: {
  variants: Plasmic_3DIcon__VariantsArgs;
  args: Plasmic_3DIcon__ArgsType;
  overrides: Plasmic_3DIcon__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sms",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.sms
      },
      {
        path: "icon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.icon
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rooticon_notification]: hasVariant(
            $state,
            "icon",
            "notification"
          ),
          [sty.rooticon_sms]: hasVariant($state, "icon", "sms"),
          [sty.rooticon_telegram]: hasVariant($state, "icon", "telegram")
        }
      )}
    >
      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__wgx6X, {
          [sty.imgicon_sms__wgx6X1Y0FX]: hasVariant($state, "icon", "sms"),
          [sty.imgicon_telegram__wgx6XwnJRu]: hasVariant(
            $state,
            "icon",
            "telegram"
          )
        })}
        displayHeight={"25px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"25px"}
        loading={"lazy"}
        src={{
          src: "/plasmic/liom_hamyar/images/image123.svg",
          fullWidth: 1500,
          fullHeight: 1500,
          aspectRatio: undefined
        }}
      />

      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__cwXb8, {
          [sty.imgicon_notification__cwXb896Mob]: hasVariant(
            $state,
            "icon",
            "notification"
          ),
          [sty.imgicon_sms__cwXb81Y0FX]: hasVariant($state, "icon", "sms"),
          [sty.imgicon_telegram__cwXb8WnJRu]: hasVariant(
            $state,
            "icon",
            "telegram"
          )
        })}
        displayHeight={"25px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"25px"}
        loading={"lazy"}
        src={{
          src: "/plasmic/liom_hamyar/images/image125.svg",
          fullWidth: 1500,
          fullHeight: 1500,
          aspectRatio: undefined
        }}
      />

      <PlasmicImg__
        alt={""}
        className={classNames(sty.img__isGdS, {
          [sty.imgicon_notification__isGdS96Mob]: hasVariant(
            $state,
            "icon",
            "notification"
          ),
          [sty.imgicon_sms__isGdS1Y0FX]: hasVariant($state, "icon", "sms"),
          [sty.imgicon_telegram__isGdSwnJRu]: hasVariant(
            $state,
            "icon",
            "telegram"
          ),
          [sty.imgsms__isGdSOqOje]: hasVariant($state, "sms", "sms")
        })}
        displayHeight={"25px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"25px"}
        loading={"lazy"}
        src={{
          src: "/plasmic/liom_hamyar/images/image124.png",
          fullWidth: 3000,
          fullHeight: 3000,
          aspectRatio: undefined
        }}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_3DIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_3DIcon__VariantsArgs;
    args?: Plasmic_3DIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<Plasmic_3DIcon__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<Plasmic_3DIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic_3DIcon__ArgProps,
          internalVariantPropNames: Plasmic_3DIcon__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_3DIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_3DIcon";
  } else {
    func.displayName = `Plasmic_3DIcon.${nodeName}`;
  }
  return func;
}

export const Plasmic_3DIcon = Object.assign(
  // Top-level Plasmic_3DIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for Plasmic_3DIcon
    internalVariantProps: Plasmic_3DIcon__VariantProps,
    internalArgProps: Plasmic_3DIcon__ArgProps
  }
);

export default Plasmic_3DIcon;
/* prettier-ignore-end */
