// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: suVPi77vb6vv9K5rYJwyxC
// Component: -eP7gX44_tLB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "../todo_mvc_app/plasmic.module.css"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectcss
import sty from "./PlasmicIconClinic2.module.css"; // plasmic-import: -eP7gX44_tLB/css

import Icon115Icon from "./icons/PlasmicIcon__Icon115"; // plasmic-import: _FBld6r6XP7e/icon
import Icon119Icon from "./icons/PlasmicIcon__Icon119"; // plasmic-import: g4oiqyMBGquL/icon
import DietFoodSvgIcon from "./icons/PlasmicIcon__DietFoodSvg"; // plasmic-import: ozXswRIM6iv_/icon
import BabyBlanketSvgIcon from "./icons/PlasmicIcon__BabyBlanketSvg"; // plasmic-import: vB7TGSAHixiu/icon
import Icon75Icon from "./icons/PlasmicIcon__Icon75"; // plasmic-import: CaIiVU2Vq7gB/icon
import MindSvgIcon from "./icons/PlasmicIcon__MindSvg"; // plasmic-import: g6DmzM6RGQ3O/icon

createPlasmicElementProxy;

export type PlasmicIconClinic2__VariantMembers = {
  unnamedGroupOfVariants: "_1" | "_2" | "_3" | "_4" | "_5" | "_6" | "_7";
};
export type PlasmicIconClinic2__VariantsArgs = {
  unnamedGroupOfVariants?: SingleChoiceArg<
    "_1" | "_2" | "_3" | "_4" | "_5" | "_6" | "_7"
  >;
};
type VariantPropType = keyof PlasmicIconClinic2__VariantsArgs;
export const PlasmicIconClinic2__VariantProps = new Array<VariantPropType>(
  "unnamedGroupOfVariants"
);

export type PlasmicIconClinic2__ArgsType = { children?: React.ReactNode };
type ArgPropType = keyof PlasmicIconClinic2__ArgsType;
export const PlasmicIconClinic2__ArgProps = new Array<ArgPropType>("children");

export type PlasmicIconClinic2__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  freeBox?: Flex__<"div">;
};

export interface DefaultIconClinic2Props {
  children?: React.ReactNode;
  unnamedGroupOfVariants?: SingleChoiceArg<
    "_1" | "_2" | "_3" | "_4" | "_5" | "_6" | "_7"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicIconClinic2__RenderFunc(props: {
  variants: PlasmicIconClinic2__VariantsArgs;
  args: PlasmicIconClinic2__ArgsType;
  overrides: PlasmicIconClinic2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "unnamedGroupOfVariants",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props.unnamedGroupOfVariants
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootunnamedGroupOfVariants__1]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_1"
          ),
          [sty.rootunnamedGroupOfVariants__2]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_2"
          ),
          [sty.rootunnamedGroupOfVariants__3]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_3"
          ),
          [sty.rootunnamedGroupOfVariants__4]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_4"
          ),
          [sty.rootunnamedGroupOfVariants__5]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_5"
          ),
          [sty.rootunnamedGroupOfVariants__6]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_6"
          ),
          [sty.rootunnamedGroupOfVariants__7]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_7"
          )
        }
      )}
    >
      <PlasmicIcon__
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        PlasmicIconType={
          hasVariant($state, "unnamedGroupOfVariants", "_7")
            ? Icon75Icon
            : hasVariant($state, "unnamedGroupOfVariants", "_6")
            ? MindSvgIcon
            : hasVariant($state, "unnamedGroupOfVariants", "_5")
            ? Icon75Icon
            : hasVariant($state, "unnamedGroupOfVariants", "_4")
            ? BabyBlanketSvgIcon
            : hasVariant($state, "unnamedGroupOfVariants", "_3")
            ? DietFoodSvgIcon
            : hasVariant($state, "unnamedGroupOfVariants", "_2")
            ? Icon119Icon
            : hasVariant($state, "unnamedGroupOfVariants", "_1")
            ? MindSvgIcon
            : Icon115Icon
        }
        className={classNames(projectcss.all, sty.svg, {
          [sty.svgunnamedGroupOfVariants__1]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_1"
          ),
          [sty.svgunnamedGroupOfVariants__2]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_2"
          ),
          [sty.svgunnamedGroupOfVariants__3]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_3"
          ),
          [sty.svgunnamedGroupOfVariants__4]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_4"
          ),
          [sty.svgunnamedGroupOfVariants__5]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_5"
          ),
          [sty.svgunnamedGroupOfVariants__6]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_6"
          ),
          [sty.svgunnamedGroupOfVariants__7]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_7"
          )
        })}
        role={"img"}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxunnamedGroupOfVariants__1]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_1"
          ),
          [sty.freeBoxunnamedGroupOfVariants__2]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_2"
          ),
          [sty.freeBoxunnamedGroupOfVariants__3]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_3"
          ),
          [sty.freeBoxunnamedGroupOfVariants__4]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_4"
          ),
          [sty.freeBoxunnamedGroupOfVariants__5]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_5"
          ),
          [sty.freeBoxunnamedGroupOfVariants__6]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_6"
          ),
          [sty.freeBoxunnamedGroupOfVariants__7]: hasVariant(
            $state,
            "unnamedGroupOfVariants",
            "_7"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: "Enter some text",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildrenunnamedGroupOfVariants__1]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_1"
            ),
            [sty.slotTargetChildrenunnamedGroupOfVariants__2]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_2"
            ),
            [sty.slotTargetChildrenunnamedGroupOfVariants__3]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_3"
            ),
            [sty.slotTargetChildrenunnamedGroupOfVariants__4]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_4"
            ),
            [sty.slotTargetChildrenunnamedGroupOfVariants__5]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_5"
            ),
            [sty.slotTargetChildrenunnamedGroupOfVariants__6]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_6"
            ),
            [sty.slotTargetChildrenunnamedGroupOfVariants__7]: hasVariant(
              $state,
              "unnamedGroupOfVariants",
              "_7"
            )
          })
        })}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "freeBox"],
  svg: ["svg"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicIconClinic2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicIconClinic2__VariantsArgs;
    args?: PlasmicIconClinic2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicIconClinic2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicIconClinic2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicIconClinic2__ArgProps,
          internalVariantPropNames: PlasmicIconClinic2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicIconClinic2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIconClinic2";
  } else {
    func.displayName = `PlasmicIconClinic2.${nodeName}`;
  }
  return func;
}

export const PlasmicIconClinic2 = Object.assign(
  // Top-level PlasmicIconClinic2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicIconClinic2
    internalVariantProps: PlasmicIconClinic2__VariantProps,
    internalArgProps: PlasmicIconClinic2__ArgProps
  }
);

export default PlasmicIconClinic2;
/* prettier-ignore-end */
