/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: suVPi77vb6vv9K5rYJwyxC
// Component: pJx-OeYDO7eh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Dialog3 from "../../Dialog3"; // plasmic-import: j5op3vcM_4hJ/component
import Subscription3 from "../../Subscription3"; // plasmic-import: vcwQDI5OpjvX/component
import Button from "../../Button"; // plasmic-import: ErJEaLhimwjN/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectcss
import sty from "./PlasmicEditCustom.module.css"; // plasmic-import: pJx-OeYDO7eh/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: rMWZc9fpVIkj/icon
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: H9d2pdUvXD_1/icon

createPlasmicElementProxy;

export type PlasmicEditCustom__VariantMembers = {};
export type PlasmicEditCustom__VariantsArgs = {};
type VariantPropType = keyof PlasmicEditCustom__VariantsArgs;
export const PlasmicEditCustom__VariantProps = new Array<VariantPropType>();

export type PlasmicEditCustom__ArgsType = {
  type?: string;
  token?: string;
  desc?: string;
  redirectUrl?: string;
  selectShop?: any;
  onSelectShopChange?: (val: string) => void;
  open?: boolean;
  onOpenChange?: (val: string) => void;
  data?: any;
  onDataChange?: (val: string) => void;
  onClick?: (event: any) => void;
  index?: any;
  onIndexChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicEditCustom__ArgsType;
export const PlasmicEditCustom__ArgProps = new Array<ArgPropType>(
  "type",
  "token",
  "desc",
  "redirectUrl",
  "selectShop",
  "onSelectShopChange",
  "open",
  "onOpenChange",
  "data",
  "onDataChange",
  "onClick",
  "index",
  "onIndexChange"
);

export type PlasmicEditCustom__OverridesType = {
  root?: Flex__<"div">;
  dialog2?: Flex__<typeof Dialog3>;
  subscription3?: Flex__<typeof Subscription3>;
  button9?: Flex__<typeof Button>;
  svg?: Flex__<"svg">;
};

export interface DefaultEditCustomProps {
  type?: string;
  token?: string;
  desc?: string;
  redirectUrl?: string;
  selectShop?: any;
  onSelectShopChange?: (val: string) => void;
  open?: boolean;
  onOpenChange?: (val: string) => void;
  data?: any;
  onDataChange?: (val: string) => void;
  onClick?: (event: any) => void;
  index?: any;
  onIndexChange?: (val: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEditCustom__RenderFunc(props: {
  variants: PlasmicEditCustom__VariantsArgs;
  args: PlasmicEditCustom__ArgsType;
  overrides: PlasmicEditCustom__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          type: "special_advice",
          desc: "\u0628\u0631\u0627\u06cc \u062f\u0633\u062a\u0631\u0633\u06cc \u0648 \u0627\u0633\u062a\u0641\u0627\u062f\u0647 \u0627\u0632 \u0627\u06cc\u0646 \u0627\u0628\u0632\u0627\u0631\u060c \u0627\u0634\u062a\u0631\u0627\u06a9 \u0648\u06cc\u0698\u0647 \u062a\u0647\u06cc\u0647 \u0646\u0645\u0627\u06cc\u06cc\u062f."
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "selectShop",
        type: "writable",
        variableType: "object",

        valueProp: "selectShop",
        onChangeProp: "onSelectShopChange"
      },
      {
        path: "dialog2.opendialog",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.open;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      },
      {
        path: "subscription3[].clickitem",
        type: "private",
        variableType: "boolean"
      },
      {
        path: "subscription3[].title",
        type: "private",
        variableType: "text"
      },
      {
        path: "subscription3[].price",
        type: "private",
        variableType: "number"
      },
      {
        path: "subscription3[].discount",
        type: "private",
        variableType: "text"
      },
      {
        path: "subscription3[].fullprice",
        type: "private",
        variableType: "number"
      },
      {
        path: "button9.color",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "open",
        type: "writable",
        variableType: "boolean",

        valueProp: "open",
        onChangeProp: "onOpenChange"
      },
      {
        path: "topShop",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.shopDialog.data.result.shopList.length == 1
                ? $state.shopDialog.data.result.shopList[0]
                : $state.shopDialog.data.result.shopList.find(
                    item => item.selected == 1
                  );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {};
              }
              throw e;
            }
          })()
      },
      {
        path: "button9.load",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "button9.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.loading;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
      },
      {
        path: "data",
        type: "writable",
        variableType: "array",

        valueProp: "data",
        onChangeProp: "onDataChange"
      },
      {
        path: "index",
        type: "writable",
        variableType: "array",

        valueProp: "index",
        onChangeProp: "onIndexChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      style={{ position: "absolute", "z-index": 300 }}
    >
      <Dialog3
        data-plasmic-name={"dialog2"}
        data-plasmic-override={overrides.dialog2}
        className={classNames("__wab_instance", sty.dialog2)}
        onOpendialogChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["dialog2", "opendialog"]).apply(
            null,
            eventArgs
          );

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }

          (async val => {
            const $steps = {};

            $steps["updateOpen"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["open"]
                    },
                    operation: 0,
                    value: $state.dialog2.opendialog
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateOpen"] != null &&
              typeof $steps["updateOpen"] === "object" &&
              typeof $steps["updateOpen"].then === "function"
            ) {
              $steps["updateOpen"] = await $steps["updateOpen"];
            }
          }).apply(null, eventArgs);
        }}
        opendialog={generateStateValueProp($state, ["dialog2", "opendialog"])}
      >
        <div className={classNames(projectcss.all, sty.freeBox__lCl2I)}>
          <div className={classNames(projectcss.all, sty.freeBox___5DgqV)}>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $state.data;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.subscription3),
                  clickitem: generateStateValueProp($state, [
                    "subscription3",
                    __plasmic_idx_0,
                    "clickitem"
                  ]),
                  discount: generateStateValueProp($state, [
                    "subscription3",
                    __plasmic_idx_0,
                    "discount"
                  ]),
                  fullprice: generateStateValueProp($state, [
                    "subscription3",
                    __plasmic_idx_0,
                    "fullprice"
                  ]),
                  key: currentIndex,
                  onClick: async event => {
                    const $steps = {};

                    $steps["updateSelectShop"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["selectShop"]
                            },
                            operation: 0,
                            value: currentItem
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateSelectShop"] != null &&
                      typeof $steps["updateSelectShop"] === "object" &&
                      typeof $steps["updateSelectShop"].then === "function"
                    ) {
                      $steps["updateSelectShop"] =
                        await $steps["updateSelectShop"];
                    }
                  },
                  onClickitemChange: async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "subscription3",
                      __plasmic_idx_0,
                      "clickitem"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  },
                  onDiscountChange: async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "subscription3",
                      __plasmic_idx_0,
                      "discount"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  },
                  onFullpriceChange: async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "subscription3",
                      __plasmic_idx_0,
                      "fullprice"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  },
                  onPriceChange: async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "subscription3",
                      __plasmic_idx_0,
                      "price"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  },
                  onTitleChange: async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "subscription3",
                      __plasmic_idx_0,
                      "title"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  },
                  price: generateStateValueProp($state, [
                    "subscription3",
                    __plasmic_idx_0,
                    "price"
                  ]),
                  title: generateStateValueProp($state, [
                    "subscription3",
                    __plasmic_idx_0,
                    "title"
                  ])
                };

                initializePlasmicStates(
                  $state,
                  [
                    {
                      name: "subscription3[].clickitem",
                      initFunc: ({ $props, $state, $queries, $q }) =>
                        (() => {
                          try {
                            return currentItem.id == $state.selectShop.id;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })()
                    },
                    {
                      name: "subscription3[].title",
                      initFunc: ({ $props, $state, $queries, $q }) =>
                        (() => {
                          try {
                            return currentItem.text;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                    },
                    {
                      name: "subscription3[].price",
                      initFunc: ({ $props, $state, $queries, $q }) =>
                        (() => {
                          try {
                            return currentItem.price.toLocaleString();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return 120000;
                            }
                            throw e;
                          }
                        })()
                    },
                    {
                      name: "subscription3[].discount",
                      initFunc: ({ $props, $state, $queries, $q }) =>
                        (() => {
                          try {
                            return currentItem.badge;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                    },
                    {
                      name: "subscription3[].fullprice",
                      initFunc: ({ $props, $state, $queries, $q }) =>
                        (() => {
                          try {
                            return currentItem.fullPrice.toLocaleString();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return 0;
                            }
                            throw e;
                          }
                        })()
                    }
                  ],
                  [__plasmic_idx_0]
                );
                return (
                  <Subscription3
                    data-plasmic-name={"subscription3"}
                    data-plasmic-override={overrides.subscription3}
                    {...child$Props}
                  >
                    {(() => {
                      try {
                        return currentItem.topBadge ? true : false;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___5IjEe
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p5Ekm
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.topBadge;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\ud83c\udf39 \u0628\u0647 \u0635\u0631\u0641\u0647 \u062a\u0631\u06cc\u0646 \ud83c\udf39";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    ) : null}
                  </Subscription3>
                );
              })();
            })}
          </div>
          <Button
            data-plasmic-name={"button9"}
            data-plasmic-override={overrides.button9}
            className={classNames("__wab_instance", sty.button9)}
            color={generateStateValueProp($state, ["button9", "color"])}
            endIcon={
              <Icon12Icon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
            isDisabled={(() => {
              try {
                return $state.loading;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
            load={generateStateValueProp($state, ["button9", "load"])}
            loading={generateStateValueProp($state, ["button9", "loading"])}
            onClick={args.onClick}
            onColorChange={async (...eventArgs: any) => {
              ((...eventArgs) => {
                generateStateOnChangeProp($state, ["button9", "color"])(
                  eventArgs[0]
                );
              }).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onLoadChange={async (...eventArgs: any) => {
              ((...eventArgs) => {
                generateStateOnChangeProp($state, ["button9", "load"])(
                  eventArgs[0]
                );
              }).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              ((...eventArgs) => {
                generateStateOnChangeProp($state, ["button9", "loading"])(
                  eventArgs[0]
                );
              }).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ome6W
              )}
            >
              {"\u0627\u0646\u062a\u062e\u0627\u0628"}
            </div>
          </Button>
        </div>
      </Dialog3>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dialog2", "subscription3", "button9", "svg"],
  dialog2: ["dialog2", "subscription3", "button9", "svg"],
  subscription3: ["subscription3"],
  button9: ["button9", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dialog2: typeof Dialog3;
  subscription3: typeof Subscription3;
  button9: typeof Button;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEditCustom__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEditCustom__VariantsArgs;
    args?: PlasmicEditCustom__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicEditCustom__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicEditCustom__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEditCustom__ArgProps,
          internalVariantPropNames: PlasmicEditCustom__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEditCustom__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEditCustom";
  } else {
    func.displayName = `PlasmicEditCustom.${nodeName}`;
  }
  return func;
}

export const PlasmicEditCustom = Object.assign(
  // Top-level PlasmicEditCustom renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dialog2: makeNodeComponent("dialog2"),
    subscription3: makeNodeComponent("subscription3"),
    button9: makeNodeComponent("button9"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicEditCustom
    internalVariantProps: PlasmicEditCustom__VariantProps,
    internalArgProps: PlasmicEditCustom__ArgProps
  }
);

export default PlasmicEditCustom;
/* prettier-ignore-end */
