/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: suVPi77vb6vv9K5rYJwyxC
// Component: gmdZmHDhwt9V

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SideEffect } from "@plasmicpkgs/plasmic-basic-components";
import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: GNNZ3K7lFVGd/codeComponent
import ReportItem from "../../ReportItem"; // plasmic-import: vKRq0RilbYHc/component
import Button from "../../Button"; // plasmic-import: ErJEaLhimwjN/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: suVPi77vb6vv9K5rYJwyxC/projectcss
import sty from "./PlasmicReport2.module.css"; // plasmic-import: gmdZmHDhwt9V/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: rMWZc9fpVIkj/icon
import Icon115Icon from "./icons/PlasmicIcon__Icon115"; // plasmic-import: _FBld6r6XP7e/icon

createPlasmicElementProxy;

export type PlasmicReport2__VariantMembers = {};
export type PlasmicReport2__VariantsArgs = {};
type VariantPropType = keyof PlasmicReport2__VariantsArgs;
export const PlasmicReport2__VariantProps = new Array<VariantPropType>();

export type PlasmicReport2__ArgsType = {
  token2?: string;
  active?: boolean;
  onActiveChange?: (val: string) => void;
  data?: any;
  data2?: any;
  onData2Change2?: (val: string) => void;
  selectchanels?: any;
  onSelectchanelsChange?: (val: string) => void;
  button2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicReport2__ArgsType;
export const PlasmicReport2__ArgProps = new Array<ArgPropType>(
  "token2",
  "active",
  "onActiveChange",
  "data",
  "data2",
  "onData2Change2",
  "selectchanels",
  "onSelectchanelsChange",
  "button2"
);

export type PlasmicReport2__OverridesType = {
  root?: Flex__<"div">;
  sideEffect?: Flex__<typeof SideEffect>;
  apiRequest?: Flex__<typeof ApiRequest>;
  reportItem?: Flex__<typeof ReportItem>;
};

export interface DefaultReport2Props {
  token2?: string;
  active?: boolean;
  onActiveChange?: (val: string) => void;
  data?: any;
  data2?: any;
  onData2Change2?: (val: string) => void;
  selectchanels?: any;
  onSelectchanelsChange?: (val: string) => void;
  button2?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReport2__RenderFunc(props: {
  variants: PlasmicReport2__VariantsArgs;
  args: PlasmicReport2__ArgsType;
  overrides: PlasmicReport2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          data: [
            {
              label:
                "\u0646\u0648\u062a\u06cc\u0641\u06cc\u06a9\u06cc\u0634\u0646",
              value: "notification",
              paid: false
            },
            {
              label: "\u062a\u0644\u06af\u0631\u0627\u0645",
              value: "telegram",
              paid: false
            },
            {
              label: "\u067e\u06cc\u0627\u0645\u06a9",
              value: "sms",
              paid: true
            }
          ]
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "apiRequest.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "apiRequest.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "apiRequest.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "token",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "start",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "end",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "select",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({})
      },
      {
        path: "active",
        type: "writable",
        variableType: "boolean",

        valueProp: "active",
        onChangeProp: "onActiveChange"
      },
      {
        path: "data2",
        type: "writable",
        variableType: "object",

        valueProp: "data2",
        onChangeProp: "onData2Change2"
      },
      {
        path: "selectchanels",
        type: "writable",
        variableType: "array",

        valueProp: "selectchanels",
        onChangeProp: "onSelectchanelsChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <SideEffect
        data-plasmic-name={"sideEffect"}
        data-plasmic-override={overrides.sideEffect}
        className={classNames("__wab_instance", sty.sideEffect)}
      />

      <div className={classNames(projectcss.all, sty.freeBox__hqJ)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__naebj
          )}
        >
          {"1000000 \u062a\u0648\u0645\u0627\u0646"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__czSdf
          )}
        >
          {
            "\u0645\u062c\u0645\u0648\u0639\u0647 \u0647\u0632\u06cc\u0646\u0647 \u0645\u0627\u0647"
          }
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__dfkb)}>
        <ApiRequest
          data-plasmic-name={"apiRequest"}
          data-plasmic-override={overrides.apiRequest}
          body={(() => {
            try {
              return {
                data: $state.data2
              };
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          className={classNames("__wab_instance", sty.apiRequest)}
          errorDisplay={null}
          loadingDisplay={
            <div className={classNames(projectcss.all, sty.freeBox__ocX3S)}>
              <div
                className={classNames(
                  projectcss.all,
                  sty.freeBox__qfs9E,
                  "shimmer"
                )}
              />

              <div
                className={classNames(
                  projectcss.all,
                  sty.freeBox__vhgb,
                  "shimmer"
                )}
              />
            </div>
          }
          method={"POST"}
          onError={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["apiRequest", "error"]).apply(
              null,
              eventArgs
            );
          }}
          onLoading={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["apiRequest", "loading"]).apply(
              null,
              eventArgs
            );
          }}
          onSuccess={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["apiRequest", "data"]).apply(
              null,
              eventArgs
            );
          }}
          shouldFetch={(() => {
            try {
              return $state.active && Object.keys($props.data).length > 0;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })()}
          url={"https://n8n.staas.ir/webhook/report/insert"}
        >
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__ldo16,
              "fade-in"
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__a4KrN)}>
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return $props.data;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const master = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kzTo)}
                    key={currentIndex}
                  >
                    <ReportItem
                      data-plasmic-name={"reportItem"}
                      data-plasmic-override={overrides.reportItem}
                      apiRequestData={$state.apiRequest.data?.results?.[0]}
                      className={classNames("__wab_instance", sty.reportItem)}
                      count={(() => {
                        try {
                          return $state.apiRequest.data.totalNotifications;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      master={master}
                      onClick={async event => {
                        const $steps = {};

                        $steps["runCode"] = true
                          ? (() => {
                              const actionArgs = {
                                customFunction: async () => {
                                  return (() => {
                                    if (
                                      master.value === "notification" &&
                                      $state.data2.hasDefaultDate
                                    ) {
                                      return "aleart";
                                    }
                                    if (
                                      $state.selectchanels.includes(
                                        master.value
                                      )
                                    ) {
                                      return ($state.selectchanels =
                                        $state.selectchanels.filter(
                                          item => item !== master.value
                                        ));
                                    } else {
                                      return $state.selectchanels.push(
                                        master.value
                                      );
                                    }
                                  })();
                                }
                              };
                              return (({ customFunction }) => {
                                return customFunction();
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["runCode"] != null &&
                          typeof $steps["runCode"] === "object" &&
                          typeof $steps["runCode"].then === "function"
                        ) {
                          $steps["runCode"] = await $steps["runCode"];
                        }

                        $steps["invokeGlobalAction"] =
                          $steps.runCode == "aleart"
                            ? (() => {
                                const actionArgs = {
                                  args: [
                                    "custom",
                                    "\u0628\u0647 \u062f\u0644\u06cc\u0644 \u0627\u0647\u0645\u06cc\u062a \u0627\u06cc\u0646 \u06cc\u0627\u062f\u0622\u0648\u0631\u06cc\u200c\u060c \u0641\u0639\u0627\u0644\u200c\u0633\u0627\u0632\u06cc \u0646\u0648\u062a\u06cc\u0641\u06cc\u06a9\u06cc\u0634\u0646 \u0627\u0645\u06a9\u0627\u0646\u200c\u067e\u0630\u06cc\u0631 \u0646\u06cc\u0633\u062a. \u0631\u0648\u0634 \u0647\u0627\u06cc \u062f\u06cc\u06af\u0631 \u0631\u0627 \u0627\u0646\u062a\u062e\u0627\u0628 \u06a9\u0646\u06cc\u062f.",
                                    "bottom-center",
                                    5000
                                  ]
                                };
                                return $globalActions[
                                  "Fragment.showToast"
                                ]?.apply(null, [...actionArgs.args]);
                              })()
                            : undefined;
                        if (
                          $steps["invokeGlobalAction"] != null &&
                          typeof $steps["invokeGlobalAction"] === "object" &&
                          typeof $steps["invokeGlobalAction"].then ===
                            "function"
                        ) {
                          $steps["invokeGlobalAction"] =
                            await $steps["invokeGlobalAction"];
                        }
                      }}
                      select={(() => {
                        try {
                          return $state.selectchanels.includes(master.value);
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()}
                      send={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iCg5C
                        )}
                      >
                        <div
                          className={projectcss.__wab_expr_html_text}
                          dangerouslySetInnerHTML={{
                            __html: (() => {
                              try {
                                return $state.data2.schedule_type == "everyYear"
                                  ? "قیمت‌ها به‌صورت یک دوره <span style='color:#552F96; font-weight:bold;'>سالانه</span> محاسبه شده‌اند."
                                  : "قیمت‌ها به‌صورت <span style='color:#552F96; font-weight:bold;'>ماهانه</span> محاسبه شده‌اند.";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u0642\u06cc\u0645\u062a\u200c\u0647\u0627 \u0628\u0647\u200c\u0635\u0648\u0631\u062a \u0645\u0627\u0647\u0627\u0646\u0647 \u0645\u062d\u0627\u0633\u0628\u0647 \u0634\u062f\u0647\u200c\u0627\u0646\u062f.";
                                }
                                throw e;
                              }
                            })()
                          }}
                        />
                      </div>
                    </ReportItem>
                  </div>
                );
              })}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cjfU)} />

            <div className={classNames(projectcss.all, sty.freeBox__hSJw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__a6D3Y
                )}
              >
                {"\u0635\u0648\u0631\u062a\u062d\u0633\u0627\u0628"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__gnola)}>
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return $state.selectchanels;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__z9IUv)}
                      key={currentIndex}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___5Sq04
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o2PRv
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (() => {
                                  const typeMap = {
                                    telegram: "تلگرام",
                                    sms: "پیامک",
                                    notification: "نوتیفیکیشن"
                                  };
                                  return `${typeMap[currentItem]}`;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7SN
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return `(${$state.apiRequest.data.totalNotifications})`;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xmREq
                        )}
                      >
                        <div
                          className={projectcss.__wab_expr_html_text}
                          dangerouslySetInnerHTML={{
                            __html: (() => {
                              try {
                                return $state.apiRequest.data.results[0].costs[
                                  currentItem
                                ] == 0
                                  ? '<span class="swiper-ltr" style="background-color:rgba(34,197,94,0.2); padding:2px 6px; border-radius:6px; font-weight:bold;">رایگان</span>'
                                  : (
                                      $state.apiRequest.data.results[0].costs[
                                        currentItem
                                      ] * 10
                                    ).toLocaleString() +
                                      ' <span style="font-size:0.85em;">ریال</span>';
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()
                          }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__pi8Zz)}>
                <div className={classNames(projectcss.all, sty.freeBox__ug39R)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9PBdN
                    )}
                  >
                    {
                      "\u00ab \u0627\u06cc\u0646 \u0645\u0628\u0644\u063a \u0647\u0646\u06af\u0627\u0645 \u0627\u0631\u0633\u0627\u0644 \u0647\u0631 \u06cc\u0627\u062f\u0622\u0648\u0631\u06cc \u0627\u0632 \u0645\u0648\u062c\u0648\u062f\u06cc \u0634\u0645\u0627 \u06a9\u0633\u0631 \u0645\u06cc\u200c\u0634\u0648\u062f \u00bb"
                    }
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5K4Xm)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__i19XF)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sSw0T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8WMGm
                        )}
                      >
                        {"\u062c\u0645\u0639 \u06a9\u0644"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nVjJw
                      )}
                    >
                      <div
                        className={projectcss.__wab_expr_html_text}
                        dangerouslySetInnerHTML={{
                          __html: (() => {
                            try {
                              return (() => {
                                const totalCost = $state.selectchanels.reduce(
                                  (sum, channel) => {
                                    const cost =
                                      $state.apiRequest.data.results[0].costs[
                                        channel
                                      ] || 0;
                                    return sum + cost;
                                  },
                                  0
                                );
                                return totalCost == 0
                                  ? '<span class="swiper-ltr" style="background-color:rgba(34,197,94,0.2); padding:2px 6px; border-radius:6px; font-weight:bold;">رایگان</span>'
                                  : totalCost.toLocaleString() +
                                      ' <span style="font-size:0.85em;">تومان</span>';
                              })();
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()
                        }}
                      />
                    </div>
                  </div>
                </div>
                {renderPlasmicSlot({
                  defaultContents: (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___3PxFt
                      )}
                    />
                  ),

                  value: args.button2
                })}
              </div>
            </div>
          </div>
        </ApiRequest>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "sideEffect", "apiRequest", "reportItem"],
  sideEffect: ["sideEffect"],
  apiRequest: ["apiRequest", "reportItem"],
  reportItem: ["reportItem"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  sideEffect: typeof SideEffect;
  apiRequest: typeof ApiRequest;
  reportItem: typeof ReportItem;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReport2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReport2__VariantsArgs;
    args?: PlasmicReport2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicReport2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicReport2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReport2__ArgProps,
          internalVariantPropNames: PlasmicReport2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReport2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicReport2";
  } else {
    func.displayName = `PlasmicReport2.${nodeName}`;
  }
  return func;
}

export const PlasmicReport2 = Object.assign(
  // Top-level PlasmicReport2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sideEffect: makeNodeComponent("sideEffect"),
    apiRequest: makeNodeComponent("apiRequest"),
    reportItem: makeNodeComponent("reportItem"),

    // Metadata about props expected for PlasmicReport2
    internalVariantProps: PlasmicReport2__VariantProps,
    internalArgProps: PlasmicReport2__ArgProps
  }
);

export default PlasmicReport2;
/* prettier-ignore-end */
